name: Remotion Render

on:
  workflow_dispatch:
    inputs:
      images:
        description: "JSON array of image URLs"
        required: true

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm ci
      - name: Render video
        env:
          IMAGES: ${{ github.event.inputs.images }}
        run: |
          npm install -g remotion @remotion/cli
          remotion render MyComp out/video.mp4 --props='{"images": $IMAGES}'
      - name: Upload video
        uses: actions/upload-artifact@v2
        with:
          name: rendered-video
          path: out/video.mp4
